## <center> Prelims 2023
### <center> Mani Tyagi
#### <center> 200973108

In [28]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pprint as pp
from scipy.linalg import qr

In [40]:
# defining matrix A1
A1 = np.array([[5, 4, 1, 8, 4, 8],
               [7, 4, 9, 1, 7, 2],
               [7, 10, 10, 3, 2, 7]])

# defining matrix A2
A2 = np.array([[5, 4, 1, 8, 4, 8],
               [7, 4, 9, 1, 7, 2],
               [-2, 10**(-5), -8, 7, -3, 6]])

# defining matrix b
b = np.array([[-1],[0],[5]])


[[-1  0  5]]


## Part (a)

In [24]:
# Implementing SVD on matrices A1 and A2
U1, S1, V1 = np.linalg.svd(A1)
print("\nMatrix U1: \n", U1)
print("\nMatrix S1: \n", S1)
print("\nMatrix V1: \n", V1.T)

# verifying using code
v4 = V1.T[:,3]
print("\nv3: \n", v4)
result = np.dot(A1, v4)
print("\nA1*v3: \n", result)

# Implementing SVD on matrix A2
U2, S2, V2 = np.linalg.svd(A2)
print("\nMatrix U2: \n", U2)
print("\nMatrix S2: \n", S2)
print("\nMatrix V2: \n", V2.T)

# verifying using code
v4 = V2.T[:,3]
print("\nv3: \n", v4)
result = np.dot(A2, v4)
print("\nA2*v3\n", result)


Matrix U1: 
 [[-0.46276071  0.84047341 -0.28188112]
 [-0.52940829 -0.51706405 -0.67258578]
 [-0.71104106 -0.16201607  0.68423052]]

Matrix S1: 
 [24.08211747  9.15140203  5.77091493]

Matrix V1: 
 [[-0.45664377 -0.06023053 -0.23010085 -0.56339395 -0.30526585 -0.56947552]
 [-0.4600545  -0.03568013  0.52408285  0.16639323  0.61207482 -0.33180062]
 [-0.51232397 -0.59370834  0.0878807   0.32313925 -0.40182549  0.33380959]
 [-0.2642881   0.6251146  -0.15161256  0.6054296  -0.3172355  -0.22184184]
 [-0.28979939 -0.06355166 -0.77408244  0.08638278  0.51963194  0.18786839]
 [-0.40437431  0.49779768  0.2061013  -0.42008879 -0.00759854  0.60800395]]

v3: 
 [-0.56339395  0.16639323  0.32313925  0.6054296   0.08638278 -0.42008879]

A1*v3: 
 [-4.44089210e-16 -2.77555756e-16  4.44089210e-16]

Matrix U2: 
 [[-0.61919612  0.53222434 -0.57735035]
 [-0.77051796 -0.27012743  0.5773502 ]
 [ 0.15132166  0.80235181  0.57735026]]

Matrix S2: 
 [1.75295926e+01 1.55149406e+01 5.46160369e-06]

Matrix V2: 
 [[-

### Part (b)

In [25]:
def pseudo_inverse(matrix):
    A_AT = matrix @ matrix.T
    return matrix.T @ np.linalg.inv(A_AT)

def calculate_x(A, b):
    A_dagger = pseudo_inverse(A)
    x = A_dagger @ b
    residual = np.linalg.norm(A@x-b)
    condition_number = np.linalg.cond(A)
    
    return x, residual, condition_number

# results for A1
x1, residual1, cond1 = calculate_x(A1, b)
print("Results for matrix A1: ")
print("--------------------------------")
print("x: \n", x1)
print("\n Residual: \n", residual1)
print("\n Condition number: \n", cond1)

# results for A2
x2, residual2, cond2 = calculate_x(A2, b)
print("\nResults for matrix A2: ")
print("--------------------------------")
print("x: \n", x2)
print("\n Residual: \n", residual2)
print("\n Condition number: \n", cond2)


Results for matrix A1: 
--------------------------------
x: 
 [[-0.07814726]
 [ 0.40180126]
 [ 0.22926105]
 [-0.17609376]
 [-0.44803083]
 [ 0.09439295]]

 Residual: 
 1.790180836524724e-15

 Condition number: 
 4.173015504465242

Results for matrix A2: 
--------------------------------
x: 
 [[-104224.3649559 ]
 [ 600105.98623747]
 [ -82030.41040039]
 [ -84641.55218124]
 [ -94650.5120163 ]
 [ -92692.28077698]]

 Residual: 
 0.0023146241247745366

 Condition number: 
 3209605.38719908


### Part (c)

In [27]:
def economy_inverse(matrix):
    U, s, V = np.linalg.svd(matrix, full_matrices=False) # economy mode of SVD
    S_inv = np.diag(1.0/s)
    return V.T @ S_inv @ U.T 

def calculate_x_economy(matrix, b):
    M = economy_inverse(matrix)
    x = M @ b 
    residual = np.linalg.norm(matrix @ x-b)
    
    return x, residual

# results for A1
x1, residual1 = calculate_x_economy(A1, b)
print("Results for matrix A1: ")
print("--------------------------------")
print("x: \n", x1)
print("\n Residual: \n", residual1)

# results for A2
x2, residual2 = calculate_x_economy(A2, b)
print("\nResults for matrix A2: ")
print("--------------------------------")
print("x: \n", x2)
print("\n Residual: \n", residual2)

Results for matrix A1: 
--------------------------------
x: 
 [[-0.07814726]
 [ 0.40180126]
 [ 0.22926105]
 [-0.17609376]
 [-0.44803083]
 [ 0.09439295]]

 Residual: 
 9.930136612989092e-16

Results for matrix A2: 
--------------------------------
x: 
 [[-104205.95747864]
 [ 600000.0002434 ]
 [ -82015.92287634]
 [ -84626.60337266]
 [ -94633.79557212]
 [ -92675.91017929]]

 Residual: 
 2.016372521837332e-09


### Part (d)

In [42]:
def solve_qr_pivoting(A, b):
    # Perform QR decomposition with pivoting
    Q, R, P = qr(A, pivoting=True)
    
    # Compute Q^T b
    Qt_b = Q.T @ b
    
    # Determine the number of rows in A
    m = A.shape[0]
    
    # Extract the relevant portion of R (first m rows and columns)
    R_tilde = R[:, :m]
    
    # Solve for y in the upper triangular system R_tilde y = Q^T b
    y = np.linalg.solve(R_tilde, Qt_b)
    
    # Construct the solution vector x
    n = A.shape[1]
    x = np.concatenate((y, np.zeros((n - m, 1))))  # Ensure zeros has the same dimension as y

    # Apply the permutation P to y
    x_permuted = np.zeros(n)
    for i, p in enumerate(P):
        x_permuted[p] = x[i]
    
    # Compute the residual
    residual = np.linalg.norm(A @ x_permuted - b)
    
    return x_permuted, residual


# Results for A1
x1, residual1 = solve_qr_pivoting(A1, b)
print("Results for matrix A1: ")
print("--------------------------------")
print("x: \n", x1.T)
print("\nResidual: \n", residual1)

# Results for A2
x2, residual2 = solve_qr_pivoting(A2, b)
print("\nResults for matrix A2: ")
print("--------------------------------")
print("x: \n", x2.T)
print("\nResidual: \n", residual2)


Results for matrix A1: 
--------------------------------
x: 
 [ 0.          0.          0.52486188  0.         -0.72375691  0.17127072]

Residual: 
 11.135528725660043

Results for matrix A2: 
--------------------------------
x: 
 [      0.          599999.99990416 -236619.70418755 -270422.66192863
       0.               0.        ]

Residual: 
 11.135528724225177


### Part (e)

In [53]:
def solve_minimize(A, b, lam):
    At_A = A.T @ A
    M = (At_A + lam*np.eye(A.shape[1]))
    M_inv = np.linalg.inv(M)
    x = np.linalg.solve(M_inv, A.T @ b)
    residual = np.linalg.norm(A @ x - b)
    return x, residual

# Lambda values to test
lambdas = [0.1, 0.01, 0.001]

# Results for A1
print("Results for matrix A1: ")
print("--------------------------------")
for lam in lambdas:
    x1, residual1 = solve_minimize(A1, b, lam)
    print(f"Lambda = {lam}:")
    print("x: \n", x1.T)
    print("Residual: \n", residual1)
    print()

# Results for A2
print("\nResults for matrix A2: ")
print("--------------------------------")
for lam in lambdas:
    x2, residual2 = solve_minimize(A2, b, lam)
    print(f"Lambda = {lam}:")
    print("x: \n", x2.T)
    print("Residual: \n", residual2)
    print()

Results for matrix A1: 
--------------------------------
Lambda = 0.1:
x: 
 [[19638.  20292.6 22945.9 10516.7 12046.6 16984.7]]
Residual: 
 1040362.1467835617

Lambda = 0.01:
x: 
 [[19635.3        20288.46       22941.48999999 10516.07
  12046.06       16982.27      ]]
Residual: 
 1040200.5644374731

Lambda = 0.001:
x: 
 [[19635.03000005 20288.04600003 22941.04900003 10516.00700005
  12046.00600004 16982.02700006]]
Residual: 
 1040184.4062172304


Results for matrix A2: 
--------------------------------
Lambda = 0.1:
x: 
 [[ -4417.49752   -1472.391035 -10676.09768    6074.70152   -5337.89768
    4786.20176 ]]
Residual: 
 239933.54818216653

Lambda = 0.01:
x: 
 [[ -4416.14752001  -1472.03103951 -10672.40768      6072.27151998
   -5336.18768001   4784.22175998]]
Residual: 
 239849.5728677618

Lambda = 0.001:
x: 
 [[ -4416.01251998  -1471.99503993 -10672.03868002   6072.02852007
   -5336.01667999   4784.02376006]]
Residual: 
 239841.17535500214

