In [2]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# defining function for Power Method
def Power_method_Rayleigh(A, x0, tol, max_iter):
    x = x0 
    eigenvalue = 0
    eigenvector = np.zeros_like(x)
    print("Iteration \t Eigenvalue \t \t EigenVector \t \t \t Convergence Rate")
    print("------------------------------------------------------------------------------")
    prev_error = 0
    for i in range(max_iter):
        x_prev = x 
        
        # Rayleigh Quotient iteration
        x = A @ x 
        # normalization of eigenvector  
        x = x / np.max(np.abs(x))
        
        eigenvalue = x.T @ A @ x 
        eigenvalue = eigenvalue/np.dot(x.T, x)
        
        # computing error 
        error = np.linalg.norm(x - x_prev, np.inf)
        
        # computing convergence
        if i > 0:
            conv_rate = error / prev_error
        else:
            conv_rate = np.nan 

        # Display iteration information
        print(f"{i+1}\t\t{eigenvalue:.8f}\t\t{np.array2string(x, precision=4, separator=',')}\t \t{conv_rate:.8f}")            
        
        # Check for convergence
        if error < tol:
            print(f"\nConverged in {i+1} iterations")
            break
        
        # Update previous error
        prev_error = error
    
    return eigenvalue, x
        

### Part 1


In [9]:
# Define the matrices A1, A2, A3
A1 = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 6]])
A2 = np.array([[3, 3, 0], [3, 5, 0], [0, 0, 7]])
A3 = np.array([[3, 1, 0], [0, 3, 0], [0, 0, 2]])

# calculating theoretical eigenvalues
e1, ev1 = np.linalg.eig(A1)
print("Eigenvalues of A1: \n", e1)
e2, ev2 = np.linalg.eig(A2)
print("\nEigenvalues of A2: \n", e2)
e3, ev3 = np.linalg.eig(A3)
print("\nEigenvalues of A3: \n", e3)

Eigenvalues of A1: 
 [7.87298335 1.         0.12701665]

Eigenvalues of A2: 
 [0.83772234 7.16227766 7.        ]

Eigenvalues of A3: 
 [3. 3. 2.]
-1.6653345369377348e-16


In [5]:
# Define initial guess
x0 = np.array([1, 1, 1])
tol = 10e-6
max_iter = 100 

# Apply Power Method to A1
print("\nMatrix A1:")
eigenvalue_A1, eigenvector_A1 = Power_method_Rayleigh(A1, x0, tol, max_iter)
print("\nDominant Eigenvalue:", eigenvalue_A1)
print("Dominant Eigenvector:", eigenvector_A1)

# Apply Power Method to A2
print("\nMatrix A2:")
eigenvalue_A2, eigenvector_A2 = Power_method_Rayleigh(A2, x0, tol, max_iter)
print("\nDominant Eigenvalue:", eigenvalue_A2)
print("Dominant Eigenvector:", eigenvector_A2)

# Apply Power Method to A3
print("\nMatrix A3:")
eigenvalue_A3, eigenvector_A3 = Power_method_Rayleigh(A3, x0, tol, max_iter)
print("\nDominant Eigenvalue:", eigenvalue_A3)
print("Dominant Eigenvector:", eigenvector_A3)


Matrix A1:
Iteration 	 Eigenvalue 	 	 EigenVector 	 	 	 Convergence Rate
------------------------------------------------------------------------------
1		7.84137931		[0.3,0.6,1. ]	 	nan
2		7.87247122		[0.2346,0.5556,1.    ]	 	0.09347443
3		7.87297508		[0.2266,0.55  ,1.    ]	 	0.12234670
4		7.87298321		[0.2256,0.5493,1.    ]	 	0.12641640
5		7.87298334		[0.2254,0.5492,1.    ]	 	0.12694030
6		7.87298335		[0.2254,0.5492,1.    ]	 	0.12700695
7		7.87298335		[0.2254,0.5492,1.    ]	 	0.12701542

Converged in 7 iterations

Dominant Eigenvalue: 7.8729833462068575
Dominant Eigenvector: [0.22540363 0.54919355 1.        ]

Matrix A2:
Iteration 	 Eigenvalue 	 	 EigenVector 	 	 	 Convergence Rate
------------------------------------------------------------------------------
1		7.10738255		[0.75 ,1.   ,0.875]	 	nan
2		7.11050604		[0.7241,1.    ,0.8448]	 	0.12068966
3		7.11212881		[0.7212,1.    ,0.8245]	 	0.67307692
4		7.11370331		[0.7208,1.    ,0.8057]	 	0.92644295
5		7.11524883		[0.7208,1.    ,0.78

### Part 2

In [12]:
# Define the matrices A1
A1 = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 6]])

# Define initial guess
x0 = np.array([-1 + np.sqrt(0.6), -0.4 * (5 + np.sqrt(15)), 2])

# Apply Power Method to A1
print("\nMatrix A1:")
eigenvalue_A1, eigenvector_A1 = Power_method_Rayleigh(A1, x0, tol, max_iter)
print("\nDominant Eigenvalue:", eigenvalue_A1)
print("Dominant Eigenvector:", eigenvector_A1)


-0.6422084038531883

Matrix A1:
Iteration 	 Eigenvalue 	 	 EigenVector 	 	 	 Convergence Rate
------------------------------------------------------------------------------
1		0.97570215		[-1.    ,-0.746 , 0.6351]	 	nan
2		0.99959696		[-1.    ,-0.5281, 0.5154]	 	0.07771161
3		0.99999349		[-1.    ,-0.5035, 0.5019]	 	0.11290696
4		0.99999990		[-1.    ,-0.5004, 0.5002]	 	0.12522733
5		1.00000000		[-1.    ,-0.5001, 0.5   ]	 	0.12678943
6		1.00000000		[-1. ,-0.5, 0.5]	 	0.12698780
7		1.00000000		[-1. ,-0.5, 0.5]	 	0.12701349

Converged in 7 iterations

Dominant Eigenvalue: 0.9999999999995596
Dominant Eigenvector: [-1.         -0.50000092  0.5000005 ]


In [7]:
eg, ev = np.linalg.eig(A1)
print(eg)
print(ev)
x0 = np.array([-1 + np.sqrt(0.6), -0.4 * (5 + np.sqrt(15)), 2])
print(x0)

[7.87298335 1.         0.12701665]
[[-0.19382266 -0.81649658  0.54384383]
 [-0.47224729 -0.40824829 -0.78122713]
 [-0.8598926   0.40824829  0.30646053]]
[-0.22540333 -3.54919334  2.        ]
