In [33]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt

In [34]:
# Function to perform Power Method
def power_method(A, x0, tol=1e-6, max_iter=100):
    x = x0
    eigenvalue = 0
    eigenvec = np.zeros_like(x)
    
    print("Iteration\tEigenvalue\t\tEigenVector\t \tConvergence Rate")
    print("--------------------------------------------------------------")
    prev_diff = 0
    for i in range(max_iter):
        x_prev = x
        
        # Power iteration
        x = A @ x
        eigenvalue = np.dot(x, x_prev)
        eigenvalue /= np.dot(x_prev, x_prev)
        
        # Normalize eigenvector
        x = x / np.max(np.abs(x))
        
        # Compute error
        error = np.linalg.norm(x - x_prev, np.inf)
        
        # Compute convergence rate
        if i > 0:
            convergence_rate = error / prev_diff
        else:
            convergence_rate = np.nan
        
        # Display iteration information
        print(f"{i+1}\t\t{eigenvalue:.8f}\t\t{x}\t \t{convergence_rate}")
        
        # Check for convergence
        if error < tol:
            print(f"\nConverged in {i+1} iterations")
            break
        
        # Update previous difference
        prev_diff = error
    
    return eigenvalue, x




### Part 1

In [35]:
# Define the matrices A1, A2, A3
A1 = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 6]])
A2 = np.array([[3, 3, 0], [3, 5, 0], [0, 0, 7]])
A3 = np.array([[3, 1, 0], [0, 3, 0], [0, 0, 2]])

# Define initial guess
x0 = np.array([1, 1, 1])

# Apply Power Method to A1
print("\nMatrix A1:")
eigenvalue_A1, eigenvector_A1 = power_method(A1, x0)
print("\nDominant Eigenvalue:", eigenvalue_A1)
print("Dominant Eigenvector:", eigenvector_A1)

# Apply Power Method to A2
print("\nMatrix A2:")
eigenvalue_A2, eigenvector_A2 = power_method(A2, x0)
print("\nDominant Eigenvalue:", eigenvalue_A2)
print("Dominant Eigenvector:", eigenvector_A2)

# Apply Power Method to A3
print("\nMatrix A3:")
eigenvalue_A3, eigenvector_A3 = power_method(A3, x0)
print("\nDominant Eigenvalue:", eigenvalue_A3)
print("Dominant Eigenvector:", eigenvector_A3)


Matrix A1:
Iteration	Eigenvalue		EigenVector	 	Convergence Rate
--------------------------------------------------------------
1		6.33333333		[0.3 0.6 1. ]	 	nan
2		7.84137931		[0.2345679  0.55555556 1.        ]	 	0.09347442680776015
3		7.87247122		[0.2265625 0.55      1.       ]	 	0.12234669811320735
4		7.87297508		[0.22555049 0.54929577 1.        ]	 	0.12641639758797335
5		7.87298321		[0.22542202 0.54920635 1.        ]	 	0.12694029571445473
6		7.87298334		[0.2254057  0.54919499 1.        ]	 	0.12700695317838054
7		7.87298335		[0.22540363 0.54919355 1.        ]	 	0.12701542162401389
8		7.87298335		[0.22540337 0.54919337 1.        ]	 	0.1270164972978861

Converged in 8 iterations

Dominant Eigenvalue: 7.8729833462068575
Dominant Eigenvector: [0.22540337 0.54919337 1.        ]

Matrix A2:
Iteration	Eigenvalue		EigenVector	 	Convergence Rate
--------------------------------------------------------------
1		7.00000000		[0.75  1.    0.875]	 	nan
2		7.10738255		[0.72413793 1.         0.844

### Part 2

In [38]:
# Define the matrices A1
A1 = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 6]])

# Define initial guess
x0 = np.array([-1 + np.sqrt(0.6), -0.4 * (5 + np.sqrt(15)), 2])

# Apply Power Method to A1
print("\nMatrix A1:")
eigenvalue_A1, eigenvector_A1 = power_method(A1, x0)
print("\nDominant Eigenvalue:", eigenvalue_A1)
print("Dominant Eigenvector:", eigenvector_A1)



Matrix A1:
Iteration	Eigenvalue		EigenVector	 	Convergence Rate
--------------------------------------------------------------
1		0.44165098		[-1.         -0.74596669  0.63508327]	 	nan
2		0.97570215		[-1.         -0.52812344  0.51544521]	 	0.07771160783669938
3		0.99959696		[-1.         -0.50352742  0.50193724]	 	0.11290695754338091
4		0.99999349		[-1.         -0.50044733  0.50024567]	 	0.12522733274482753
5		0.99999990		[-1.         -0.50005681  0.5000312 ]	 	0.12678942617398725
6		1.00000000		[-1.         -0.50000722  0.50000396]	 	0.1269878009591921
7		1.00000000		[-1.         -0.50000092  0.5000005 ]	 	0.12701349245380836
8		1.00000000		[-1.         -0.50000012  0.50000006]	 	0.12704745756554975

Converged in 8 iterations

Dominant Eigenvalue: 0.9999999999995596
Dominant Eigenvector: [-1.         -0.50000012  0.50000006]


In [41]:
eg, ev = np.linalg.eig(A1)
print(eg)
print(ev)

[7.87298335 1.         0.12701665]
[[-0.19382266 -0.81649658  0.54384383]
 [-0.47224729 -0.40824829 -0.78122713]
 [-0.8598926   0.40824829  0.30646053]]
