### <center> Prelims 2017: Ques-5
#### <center> Mani Tyagi
##### <center> mt22t 200973108

In [16]:
# importing libraries
import numpy as np
import pprint as pp
import matplotlib.pyplot as plt

### Part (b)

In [19]:
def generate_A(N):
    '''------------------------------------------
    @brief - This function generates a tridiagonal matrix A.
    
    @param N - size of tridiagonal matrix
    @return A tridiagonal matrix
    ---------------------------------------------'''
    
    A = np.zeros((N,N))
    
    for i in range(N):
        # main diagonal
        A[i][i] = 2
        
        # superdiagonal
        if i < N - 1:
            A[i][i+1] = -1
        
        # subdiagonal
        if i > 0:
            A[i][i-1] = -1
    
    return A


In [30]:
N = 8
A = generate_A(N)

# printing matrix
print("Matrix A:")
pp.pprint(A)

B = np.linalg.inv(A)
B = B * ((N+1))
print("Matrix B:")
pp.pprint(B)

Matrix A:
array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  2.]])
Matrix B:
array([[ 8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.],
       [ 7., 14., 12., 10.,  8.,  6.,  4.,  2.],
       [ 6., 12., 18., 15., 12.,  9.,  6.,  3.],
       [ 5., 10., 15., 20., 16., 12.,  8.,  4.],
       [ 4.,  8., 12., 16., 20., 15., 10.,  5.],
       [ 3.,  6.,  9., 12., 15., 18., 12.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12., 14.,  7.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]])


### Part (c)

In [46]:
# Function to extract the Bij(k) matrix
def extract_block(B, i, j, k):
    """
    Extracts the Bij(k) matrix from the partitioned matrix B.
    
    Args:
    - B: Partitioned matrix B
    - i, j: Indices of the block within the partitioned matrix B
    - k: Level of the block within the partitioning
    
    Returns:
    - Block matrix Bij(k)
    """
    # Calculate the size of the blocks at level k
    block_size = B.shape[0] // (2 ** k)
    
    # Calculate the starting and ending row indices of the block
    start_row = (i * block_size)
    end_row = start_row + block_size
    
    # Calculate the starting and ending column indices of the block
    start_col = (j * block_size)
    end_col = start_col + block_size
    
    # Extract the block from the partitioned matrix B
    block = B[start_row:end_row, start_col:end_col]
    
    return block


# Define the indices for the blocks
blocks = [
    ("11", 2), ("12", 2),
    ("21", 2), ("22", 2),
    ("33", 2), ("34", 2),
    ("43", 2), ("44", 2),
    ("12", 1), ("21", 1)
]

# Extract and print each block matrix
for block_index, level in blocks:
    block = extract_block(B, int(block_index[0]) - 1, int(block_index[1]) - 1, level)
    print(f"B_{block_index}^({level}) matrix:")
    pp.pprint(block)
    print("\n")


B_11^(2) matrix:
array([[ 8.,  7.],
       [ 7., 14.]])


B_12^(2) matrix:
array([[ 6.,  5.],
       [12., 10.]])


B_21^(2) matrix:
array([[ 6., 12.],
       [ 5., 10.]])


B_22^(2) matrix:
array([[18., 15.],
       [15., 20.]])


B_33^(2) matrix:
array([[20., 15.],
       [15., 18.]])


B_34^(2) matrix:
array([[10.,  5.],
       [12.,  6.]])


B_43^(2) matrix:
array([[10., 12.],
       [ 5.,  6.]])


B_44^(2) matrix:
array([[14.,  7.],
       [ 7.,  8.]])


B_12^(1) matrix:
array([[ 4.,  3.,  2.,  1.],
       [ 8.,  6.,  4.,  2.],
       [12.,  9.,  6.,  3.],
       [16., 12.,  8.,  4.]])


B_21^(1) matrix:
array([[ 4.,  8., 12., 16.],
       [ 3.,  6.,  9., 12.],
       [ 2.,  4.,  6.,  8.],
       [ 1.,  2.,  3.,  4.]])




### Part (d)

In [58]:
# SVD of B_12_1
B_12_1 = extract_block(B, 0, 1, 1)
print("B_12^1: ")
pp.pprint(B_12_1)

U1, S1, V1 = np.linalg.svd(B_12_1)

print("\n")
print("U: ", U1)
print("\n")
print("V: ", V1)
print("\n")
print("S: ", S1)
print("\n")

# SVD of B_12_2
B_12_2 = extract_block(B, 0, 1, 2)
print("B_12^2: ")
pp.pprint(B_12_2)

U2, S2, V2 = np.linalg.svd(B_12_2)

print("\n")
print("U: ", U2)
print("\n")
print("V: ", V2)
print("\n")
print("S: ", S2)


B_12^1: 
array([[ 4.,  3.,  2.,  1.],
       [ 8.,  6.,  4.,  2.],
       [12.,  9.,  6.,  3.],
       [16., 12.,  8.,  4.]])


U:  [[-0.18257419  0.96684558  0.13061956  0.12171612]
 [-0.36514837  0.10192389 -0.67862484 -0.62908387]
 [-0.54772256 -0.1408591  -0.39669967  0.72304086]
 [-0.73029674 -0.18702902  0.60418228 -0.25816774]]


V:  [[-7.30296743e-01 -5.47722558e-01 -3.65148372e-01 -1.82574186e-01]
 [-6.81772874e-01  5.46724871e-01  4.34766754e-01  2.17383377e-01]
 [-4.30396826e-02  6.33318179e-01 -6.91118323e-01 -3.45559161e-01]
 [-0.00000000e+00 -5.00095444e-17  4.47213595e-01 -8.94427191e-01]]


S:  [3.00000000e+01 2.46977093e-15 7.82382963e-16 6.13655784e-33]


B_12^2: 
array([[ 6.,  5.],
       [12., 10.]])


U:  [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


V:  [[-0.76822128 -0.6401844 ]
 [-0.6401844   0.76822128]]


S:  [17.4642492  0.       ]


B